// <auto-generated />
namespace KymdanMM.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class upup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(upup));
        
        string IMigrationMetadata.Id
        {
            get { return "201404160224064_upup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
